name: Bug Report
description: Report an issue about using Li10 Governance
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
      value: "When I ordered a coffee, I received a tea instead."
    validations:
      required: true
  - type: textarea
    id: expected-bahavior
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: What were you expecting to happen?
      value: "I expected to find my keys in my pocket, but instead, I found a banana!"
    validations:
      required: true
  - type: dropdown
    id: cloud-provider
    attributes:
      label: Cloud Provider
      description: Which cloud provider are you using?
      default: 0
      options:
        - Amazon Web Services (AWS)
    validations:
      required: false
  - type: textarea
    id: version
    attributes:
      label: Cloud Custodian version and dependency information
      description: Please run `custodian version --debug` and paste the output here.
      render: shell
    validations:
      required: true
  - type: textarea
    id: policy
    attributes:
      label: Policy
      description: Please copy and paste the policy you are trying to run if applicable. Please exclude any account/sensitive information. Your response will be automatically formatted into YAML, so code-formatting markdown is not necessary.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log/traceback output
      description: Please copy and paste any relevant log output. Please exclude any account/sensitive information. Your response will be automatically formatted into YAML, so code-formatting markdown is not necessary.
      render: shell
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
      label: Extra information or context
      description: Add any other context about the problem here.
    validations:
      required: true
