name: Feature Request
description: Suggest an idea for Li10 Governance
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature enhancement!
  - type: textarea
    id: describe-feature
    attributes:
      label: Describe the feature
      description: Is your feature request related to a problem?
      placeholder: Please describe
      value: "It always irritates me when ..."
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
      label: Extra information or context
      description: Please feel free to suggest any workarounds or alternatives you might have.
